### ISSUE TITLE
Not compatible with latest muzei

### ISSUE THREAD

**Issue by MCMic** [igoralmeida/muzei-apod#5]
NASA APOD is now listed in legacy sources with a warning, I suspect this means muzei-apod needs to move to api v3 of muzei.

(It seems documentation is on the release page only: https://github.com/romannurik/muzei/issues/585 )

**Comment by igoralmeida** [comment]
Took some time today to do this, and after a lot of head scratching I think I've managed to get a very simple port to v3 working
It targets F-Droid's version, 3.0.2.
I'll test for a day or two and push if nothing else breaks.

**Comment by igoralmeida** [comment]
The updated version was submitted at https://gitlab.com/fdroid/fdroiddata/merge_requests/4307

**Comment by MCMic** [comment]
Thanks a lot, that was fast!

When I saw last commit from 2016 I thought this would not get updated…
